### ISSUE TITLE
install pyserial on some platforms.

### ISSUE THREAD

**Issue by Defragster** [digistump/OakRestore#1]
Please point to a working pyserial for Python 2.7

I have a Windows 10 system with working Python 2.7 - but I can't find a working pySerial to install and apparently it is needed to run the OakRestore which it seems I need.

Python 2.7 was indicated as needed and is working for Generic ESP8266 Arduino IDE OTA updates.

The Sourceforge and other pyserial implementations I get "No Python installation found in the registry."

Python install comes up in my DOS box - it is on the path - but apparently didn't leave a registry marker to its install and I cannot specify the needed path in the installer.

BTW: I think I need this as my on air OAK has a non-local IP address and when I connect to it 'succesfully' the gateway IP is not indicated to connect to.

With PUTTY on my serial adapter I get this that suggests my OAK got an initial update?
 ets Jan  8 2013,rst cause:2, boot mode:(3,0)

load 0x40100000, len 3632, room 16
tail 0
chksum 0xc0
load 0x3ffe8000, len 352, room 8
tail 8
chksum 0x82
csum 0x82

OakBoot v1 - N,BU,0

**Comment by digistump** [comment]
I use python 2.7 on windows and haven't needed pyserial, that line was simply repeating what others using the esptool.py had said, it should work for you without it - is there an error when you run esptool.py making you think you need it?

The boot message doesn't say anything about what version you have - for that you need to connect to the oak or send the serial command "info\n0\n" to it (making sure you are only sending those new lines) and look for "version-string":"1.0.0" if it is updated

Not sure what you mean about the Oak's ip address - when you connect to the ACORNXXXXXX and go to 192.168.0.1 in your browser, what happens?

**Comment by Defragster** [comment]
I misread "OakBoot **v1** - N,BU,0" as version info it seems.  Opening TeraTerm or PUTTY that show the startup text indicated when I type "info\n0\n" I see the FTDI lights Tx - but get no OAK Rx

On my phone indeed with 192.168.0.1 I again see "Soft AP Setup".

I did the setup and now see: 'Your Oak is connected to the cloud ...'

My device does not show on particle.io - to add I need a Device ID?

Running the script line I got stopped with this:
C:\Users\Tim\Documents\GitHub\OakRestore>python esptool.py --baud 115200 --port com10 write_flash -fs 32m 0x1000 blank.bin 0x2000 oaksetup_restore.bin 0x0081000 oakupdate_restore.bin 0x101000 blank.bin 0x102000 blank.bin 0x202000 blank.bin 
Traceback (most recent call last):
  File "esptool.py", line 22, in <module>
    import serial
ImportError: No module named serial

C:\Users\Tim\Documents\GitHub\OakRestore>

**Comment by Defragster** [comment]
Correction - there was now a device needing a name - I now have it's Device ID.

It looks like I don't need the OakRestore - but the script still wants 'serial'?

**Comment by digistump** [comment]
Yes sounds like you are good to go on your oak

I'm making a standalone exe of the esptool.py script for restoring in
windows - because I don't always get what python wants under windows either

**Comment by digistump** [comment]
Can you run this from command line: https://github.com/digistump/OakRestore/blob/master/esptool.exe - no need to actually flash your device since it is working, but if you can let me know if a command like below works, I'd appreciate knowing that I got it packaged as an exe correctly.

```
esptool --port COMX --baud 115200 read_mac

```

You'll need to power it up with Pin2 connected to GND to put it in bootloader mode.

If it works then that should save you installing python if you ever need to use this tool.

BTW: The esptool included with the generic esp8266 arduino IDE package is an entirely different tool, and it doesn't set the first bytes of flash correctly to tell the esp8266 what size flash it has installed, this creates major issues when mapping more than 1MB of flash for user applications.

**Comment by Defragster** [comment]
Running that after a Github SYNC [Pin2 connected to GND] worked resulting in:
C:\Users\Tim\Documents\GitHub\OakRestore>esptool --port COM10 --baud 115200 read_mac
Connecting...
MAC: 18:fe:34:0b:xx:xx

I seem to have made it through the Beta Hoops ("C:...\GitHub\OakCLI\builds\windows\oak.exe") and uploaded a sketch.
In Arduino I do not see "Examples / OAK"

**Comment by Defragster** [comment]
can't edit comment - I see I missed the pin hold reboot . . . back in a minute.

**Comment by digistump** [comment]
There are no examples included yet - this is intended purely as a
firmware/ota beta

Looks like you need to change COMX to be the COM port of your adapter.

**Comment by Defragster** [comment]
See above - it worked with the device held to PGM on boot.

No Beta Examples makes sense - I only follow the directions half the time - usually expecting the wrong half to work ;-)

**Comment by digistump** [comment]
Awesome - thanks for testing it!

**Comment by Defragster** [comment]
Glad to help get it more usable!
FireFox let me edit comments.

I picked this up - before enabling a pin as output it is best to put a known value on it:
  // initialize the digital pin as an output.
  digitalWrite(1, HIGH);   // turn the LED on (HIGH is the voltage level)
  pinMode(1, OUTPUT); //LED on Model A

**Comment by Defragster** [comment]
Was this a recent addition to clean up the device booting? "esptool  ... set the first bytes of flash correctly to tell the esp8266 what size flash"

**Comment by digistump** [comment]
Nope it is an old feature of esptool.py which came long before the esptool found in generic esp8266 distro (which is actually called esptool-ck) - it is also present in Espressif's original tools

Link: https://github.com/themadinventor/esptool

**Comment by Defragster** [comment]
Okay - I was running from the OAK github directory so had the right tool.

I suppose you saw on KS how IDE resetting the CODE/SPIFFS messed up my Generic ESP device. Something like that could have related to what I saw bricking OAKs - taking the OTA update offline like it did for me.

One other unanswered KS note was the persistence of the DigiStump ESP8266 toolchain, it was being used on my Generics and it stayed after I pulled out the JSON and deleted the OAK from Boards. I'm wondering if there is a missing 'differentiating element' that might have OAK toolchain interefere with any generic ESP8266 work at some point?

**Comment by digistump** [comment]
ESP8266 and OAK use identical copies of the compiler from the same download
location - Arduino IDE doesn't seem to know how to handle that and uses
them interchangeably - no risk to either project as if the compiler
version/download for one ever differed at all from the other then the
Arduino IDE would do the right thing. But it is another of many bugs with
how Arduino handles third party boards.

**Comment by Defragster** [comment]
Good enough that you know about it, and ideally that they will be shared harmlessly. Just didn't want it to be a surprise one day.
